# Generated by Django 5.0.1 on 2024-02-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0002_alter_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
