# Generated by Django 5.0.1 on 2024-02-23 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0003_post_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to="blog_app.author",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="post",
            field=models.ManyToManyField(to="blog_app.post"),
        ),
    ]
