# Generated by Django 5.0.1 on 2024-02-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0005_remove_tag_post_post_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="post"),
        ),
    ]
