# Generated by Django 5.0.1 on 2024-02-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0006_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="upload_images",
            field=models.ImageField(null=True, upload_to="post"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.CharField(max_length=100),
        ),
    ]
