# Generated by Django 5.0.1 on 2024-02-28 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0009_alter_post_image_commentsmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentsmodel",
            options={"verbose_name": "Comment", "verbose_name_plural": "Comments"},
        ),
    ]
